# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coEvolution.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1199, 491)
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1200, 490))
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.unitTab = QtWidgets.QWidget()
        self.unitTab.setObjectName("unitTab")
        self.widget = QtWidgets.QWidget(self.unitTab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 461))
        self.widget.setStyleSheet("background-color: rgb(224, 227, 255);")
        self.widget.setObjectName("widget")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(510, 0, 671, 451))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.widget_5)
        self.graphicsView_3.setGeometry(QtCore.QRect(0, 30, 331, 191))
        self.graphicsView_3.setStyleSheet("border-image: url(:/chart/3.jpg);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.widget_5, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.widget_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_6.setObjectName("widget_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.widget_6)
        self.graphicsView_7.setGeometry(QtCore.QRect(0, 30, 331, 191))
        self.graphicsView_7.setStyleSheet("border-image: url(:/chart/10.png);")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.widget_6, 1, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.widget_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.widget_4)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 30, 331, 191))
        self.graphicsView_2.setStyleSheet("border-image: url(:/chart/1.jpg);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.widget_4, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_3)
        self.graphicsView.setGeometry(QtCore.QRect(0, 30, 331, 191))
        self.graphicsView.setStyleSheet("border-image: url(:/chart/2.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.widget)
        self.label_79.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.label_79.setObjectName("label_79")
        self.label_85 = QtWidgets.QLabel(self.widget)
        self.label_85.setGeometry(QtCore.QRect(280, 30, 61, 20))
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.widget)
        self.label_86.setGeometry(QtCore.QRect(280, 170, 61, 20))
        self.label_86.setObjectName("label_86")
        self.label_88 = QtWidgets.QLabel(self.widget)
        self.label_88.setGeometry(QtCore.QRect(280, 310, 121, 20))
        self.label_88.setObjectName("label_88")
        self.listWidget_32 = QtWidgets.QListWidget(self.widget)
        self.listWidget_32.setGeometry(QtCore.QRect(80, 30, 161, 191))
        self.listWidget_32.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_32.setObjectName("listWidget_32")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 230, 231, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_89 = QtWidgets.QLabel(self.layoutWidget)
        self.label_89.setObjectName("label_89")
        self.gridLayout_2.addWidget(self.label_89, 0, 0, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_49.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_2.addWidget(self.lineEdit_49, 0, 1, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.layoutWidget)
        self.label_80.setObjectName("label_80")
        self.gridLayout_2.addWidget(self.label_80, 1, 0, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_43.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_2.addWidget(self.lineEdit_43, 1, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.layoutWidget)
        self.label_81.setObjectName("label_81")
        self.gridLayout_2.addWidget(self.label_81, 2, 0, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_44.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_2.addWidget(self.lineEdit_44, 2, 1, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.layoutWidget)
        self.label_82.setObjectName("label_82")
        self.gridLayout_2.addWidget(self.label_82, 3, 0, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_45.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_2.addWidget(self.lineEdit_45, 3, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.layoutWidget)
        self.label_83.setObjectName("label_83")
        self.gridLayout_2.addWidget(self.label_83, 4, 0, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_46.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_2.addWidget(self.lineEdit_46, 4, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.layoutWidget)
        self.label_84.setObjectName("label_84")
        self.gridLayout_2.addWidget(self.label_84, 5, 0, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_47.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_2.addWidget(self.lineEdit_47, 5, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.layoutWidget)
        self.label_87.setObjectName("label_87")
        self.gridLayout_2.addWidget(self.label_87, 6, 0, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_48.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_2.addWidget(self.lineEdit_48, 6, 1, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.layoutWidget)
        self.label_106.setObjectName("label_106")
        self.gridLayout_2.addWidget(self.label_106, 7, 0, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_57.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_2.addWidget(self.lineEdit_57, 7, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(340, 30, 131, 421))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.listWidget_14 = QtWidgets.QListWidget(self.layoutWidget_2)
        self.listWidget_14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_14.setObjectName("listWidget_14")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_14.addItem(item)
        self.verticalLayout_19.addWidget(self.listWidget_14)
        self.listWidget_15 = QtWidgets.QListWidget(self.layoutWidget_2)
        self.listWidget_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_15.setObjectName("listWidget_15")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_15.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_15.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_15.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_15.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_15.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_15.addItem(item)
        self.verticalLayout_19.addWidget(self.listWidget_15)
        self.listWidget_16 = QtWidgets.QListWidget(self.layoutWidget_2)
        self.listWidget_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_16.setObjectName("listWidget_16")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_16.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_16.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_16.addItem(item)
        self.verticalLayout_19.addWidget(self.listWidget_16)
        self.tabWidget_2.addTab(self.unitTab, "")
        self.advisorTab = QtWidgets.QWidget()
        self.advisorTab.setObjectName("advisorTab")
        self.widget_2 = QtWidgets.QWidget(self.advisorTab)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1200, 451))
        self.widget_2.setStyleSheet("background-color: rgb(224, 227, 255);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.widget_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(520, 0, 661, 451))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsView_22 = QtWidgets.QGraphicsView(self.gridLayoutWidget_6)
        self.graphicsView_22.setStyleSheet("border-image: url(:/patterns/5.png);")
        self.graphicsView_22.setObjectName("graphicsView_22")
        self.gridLayout_6.addWidget(self.graphicsView_22, 0, 0, 1, 1)
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.gridLayoutWidget_6)
        self.graphicsView_4.setStyleSheet("border-image: url(:/chart/7.png);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_6.addWidget(self.graphicsView_4, 0, 1, 1, 1)
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.gridLayoutWidget_6)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.gridLayout_6.addWidget(self.graphicsView_6, 1, 1, 1, 1)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.gridLayoutWidget_6)
        self.graphicsView_5.setStyleSheet("border-image: url(:/chart/10.png);")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_6.addWidget(self.graphicsView_5, 1, 0, 1, 1)
        self.label_165 = QtWidgets.QLabel(self.widget_2)
        self.label_165.setGeometry(QtCore.QRect(20, 30, 61, 20))
        self.label_165.setObjectName("label_165")
        self.label_171 = QtWidgets.QLabel(self.widget_2)
        self.label_171.setGeometry(QtCore.QRect(280, 30, 61, 20))
        self.label_171.setObjectName("label_171")
        self.listWidget_24 = QtWidgets.QListWidget(self.widget_2)
        self.listWidget_24.setGeometry(QtCore.QRect(350, 30, 131, 171))
        self.listWidget_24.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_24.setObjectName("listWidget_24")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_24.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_24.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_24.addItem(item)
        self.listWidget_22 = QtWidgets.QListWidget(self.widget_2)
        self.listWidget_22.setGeometry(QtCore.QRect(80, 30, 151, 171))
        self.listWidget_22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.listWidget_22.setObjectName("listWidget_22")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_22.addItem(item)
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(12, 210, 221, 126))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_175 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_175.setObjectName("label_175")
        self.gridLayout_3.addWidget(self.label_175, 0, 0, 1, 1)
        self.lineEdit_95 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_95.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_95.setObjectName("lineEdit_95")
        self.gridLayout_3.addWidget(self.lineEdit_95, 0, 1, 1, 1)
        self.label_167 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_167.setObjectName("label_167")
        self.gridLayout_3.addWidget(self.label_167, 1, 0, 1, 1)
        self.lineEdit_90 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_90.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.gridLayout_3.addWidget(self.lineEdit_90, 1, 1, 1, 1)
        self.label_169 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_169.setObjectName("label_169")
        self.gridLayout_3.addWidget(self.label_169, 2, 0, 1, 1)
        self.lineEdit_92 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_92.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.gridLayout_3.addWidget(self.lineEdit_92, 2, 1, 1, 1)
        self.label_170 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_170.setObjectName("label_170")
        self.gridLayout_3.addWidget(self.label_170, 3, 0, 1, 1)
        self.lineEdit_93 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_93.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.gridLayout_3.addWidget(self.lineEdit_93, 3, 1, 1, 1)
        self.label_184 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_184.setObjectName("label_184")
        self.gridLayout_3.addWidget(self.label_184, 4, 0, 1, 1)
        self.lineEdit_94 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_94.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_94.setObjectName("lineEdit_94")
        self.gridLayout_3.addWidget(self.lineEdit_94, 4, 1, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(260, 210, 225, 100))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_176 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_176.setObjectName("label_176")
        self.gridLayout_12.addWidget(self.label_176, 0, 0, 1, 1)
        self.lineEdit_96 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_96.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_96.setObjectName("lineEdit_96")
        self.gridLayout_12.addWidget(self.lineEdit_96, 0, 1, 1, 1)
        self.label_174 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_174.setObjectName("label_174")
        self.gridLayout_12.addWidget(self.label_174, 1, 0, 1, 1)
        self.lineEdit_102 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_102.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_102.setObjectName("lineEdit_102")
        self.gridLayout_12.addWidget(self.lineEdit_102, 1, 1, 1, 1)
        self.label_181 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_181.setObjectName("label_181")
        self.gridLayout_12.addWidget(self.label_181, 2, 0, 1, 1)
        self.lineEdit_103 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_103.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_103.setObjectName("lineEdit_103")
        self.gridLayout_12.addWidget(self.lineEdit_103, 2, 1, 1, 1)
        self.label_172 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_172.setObjectName("label_172")
        self.gridLayout_12.addWidget(self.label_172, 3, 0, 1, 1)
        self.lineEdit_97 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_97.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_97.setObjectName("lineEdit_97")
        self.gridLayout_12.addWidget(self.lineEdit_97, 3, 1, 1, 1)
        self.tabWidget_2.addTab(self.advisorTab, "")
        self.monitorTab = QtWidgets.QWidget()
        self.monitorTab.setObjectName("monitorTab")
        self.widget_16 = QtWidgets.QWidget(self.monitorTab)
        self.widget_16.setGeometry(QtCore.QRect(0, -1, 1201, 451))
        self.widget_16.setStyleSheet("background-color: rgb(224, 227, 255);")
        self.widget_16.setObjectName("widget_16")
        self.listWidget_25 = QtWidgets.QListWidget(self.widget_16)
        self.listWidget_25.setGeometry(QtCore.QRect(350, 30, 121, 171))
        self.listWidget_25.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_25.setObjectName("listWidget_25")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_25.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_25.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_25.addItem(item)
        self.label_173 = QtWidgets.QLabel(self.widget_16)
        self.label_173.setGeometry(QtCore.QRect(280, 30, 61, 20))
        self.label_173.setObjectName("label_173")
        self.label_105 = QtWidgets.QLabel(self.widget_16)
        self.label_105.setGeometry(QtCore.QRect(20, 30, 61, 20))
        self.label_105.setObjectName("label_105")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.widget_16)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(520, 0, 661, 451))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.graphicsView_30 = QtWidgets.QGraphicsView(self.gridLayoutWidget_7)
        self.graphicsView_30.setStyleSheet("border-image: url(:/patterns/6.png);")
        self.graphicsView_30.setObjectName("graphicsView_30")
        self.gridLayout_11.addWidget(self.graphicsView_30, 0, 0, 1, 1)
        self.graphicsView_31 = QtWidgets.QGraphicsView(self.gridLayoutWidget_7)
        self.graphicsView_31.setStyleSheet("border-image: url(:/chart/8.png);\n"
"")
        self.graphicsView_31.setObjectName("graphicsView_31")
        self.gridLayout_11.addWidget(self.graphicsView_31, 0, 1, 1, 1)
        self.graphicsView_32 = QtWidgets.QGraphicsView(self.gridLayoutWidget_7)
        self.graphicsView_32.setStyleSheet("border-image: url(:/chart/10.png);\n"
"border-image: url(:/chart/9.png);")
        self.graphicsView_32.setObjectName("graphicsView_32")
        self.gridLayout_11.addWidget(self.graphicsView_32, 1, 0, 1, 1)
        self.graphicsView_33 = QtWidgets.QGraphicsView(self.gridLayoutWidget_7)
        self.graphicsView_33.setObjectName("graphicsView_33")
        self.gridLayout_11.addWidget(self.graphicsView_33, 1, 1, 1, 1)
        self.listWidget_17 = QtWidgets.QListWidget(self.widget_16)
        self.listWidget_17.setGeometry(QtCore.QRect(80, 30, 141, 171))
        self.listWidget_17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_17.setObjectName("listWidget_17")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_17.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_17.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_17.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_17.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_17.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_17.addItem(item)
        self.layoutWidget_5 = QtWidgets.QWidget(self.widget_16)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 210, 213, 74))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_177 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_177.setObjectName("label_177")
        self.gridLayout_13.addWidget(self.label_177, 0, 0, 1, 1)
        self.lineEdit_98 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_98.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.gridLayout_13.addWidget(self.lineEdit_98, 0, 1, 1, 1)
        self.label_178 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_178.setObjectName("label_178")
        self.gridLayout_13.addWidget(self.label_178, 1, 0, 1, 1)
        self.lineEdit_99 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_99.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_99.setObjectName("lineEdit_99")
        self.gridLayout_13.addWidget(self.lineEdit_99, 1, 1, 1, 1)
        self.label_185 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_185.setObjectName("label_185")
        self.gridLayout_13.addWidget(self.label_185, 2, 0, 1, 1)
        self.lineEdit_106 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_106.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_106.setObjectName("lineEdit_106")
        self.gridLayout_13.addWidget(self.lineEdit_106, 2, 1, 1, 1)
        self.layoutWidget_6 = QtWidgets.QWidget(self.widget_16)
        self.layoutWidget_6.setGeometry(QtCore.QRect(250, 210, 225, 100))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_179 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_179.setObjectName("label_179")
        self.gridLayout_14.addWidget(self.label_179, 0, 0, 1, 1)
        self.lineEdit_100 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_100.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_100.setObjectName("lineEdit_100")
        self.gridLayout_14.addWidget(self.lineEdit_100, 0, 1, 1, 1)
        self.label_182 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_182.setObjectName("label_182")
        self.gridLayout_14.addWidget(self.label_182, 1, 0, 1, 1)
        self.lineEdit_104 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_104.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_104.setObjectName("lineEdit_104")
        self.gridLayout_14.addWidget(self.lineEdit_104, 1, 1, 1, 1)
        self.label_183 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_183.setObjectName("label_183")
        self.gridLayout_14.addWidget(self.label_183, 2, 0, 1, 1)
        self.lineEdit_105 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_105.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_105.setObjectName("lineEdit_105")
        self.gridLayout_14.addWidget(self.lineEdit_105, 2, 1, 1, 1)
        self.label_180 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_180.setObjectName("label_180")
        self.gridLayout_14.addWidget(self.label_180, 3, 0, 1, 1)
        self.lineEdit_101 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_101.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_101.setObjectName("lineEdit_101")
        self.gridLayout_14.addWidget(self.lineEdit_101, 3, 1, 1, 1)
        self.tabWidget_2.addTab(self.monitorTab, "")

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "自律变化曲线"))
        self.label_4.setText(_translate("Form", "关系变化曲线"))
        self.label_2.setText(_translate("Form", "自信变化曲线"))
        self.label.setText(_translate("Form", "资源变化曲线"))
        self.label_79.setText(_translate("Form", "仿真成员："))
        self.label_85.setText(_translate("Form", "建议者："))
        self.label_86.setText(_translate("Form", "监控者："))
        self.label_88.setText(_translate("Form", "连接单元："))
        __sortingEnabled = self.listWidget_32.isSortingEnabled()
        self.listWidget_32.setSortingEnabled(False)
        item = self.listWidget_32.item(0)
        item.setText(_translate("Form", "unit1"))
        item = self.listWidget_32.item(1)
        item.setText(_translate("Form", "unit2"))
        item = self.listWidget_32.item(2)
        item.setText(_translate("Form", "unit3"))
        item = self.listWidget_32.item(3)
        item.setText(_translate("Form", "unit4"))
        item = self.listWidget_32.item(4)
        item.setText(_translate("Form", "unit5"))
        item = self.listWidget_32.item(5)
        item.setText(_translate("Form", "unit6"))
        item = self.listWidget_32.item(6)
        item.setText(_translate("Form", "unit7"))
        item = self.listWidget_32.item(7)
        item.setText(_translate("Form", "unit8"))
        item = self.listWidget_32.item(8)
        item.setText(_translate("Form", "unit9"))
        item = self.listWidget_32.item(9)
        item.setText(_translate("Form", "unit10"))
        item = self.listWidget_32.item(10)
        item.setText(_translate("Form", "unit11"))
        item = self.listWidget_32.item(11)
        item.setText(_translate("Form", "unit12"))
        item = self.listWidget_32.item(12)
        item.setText(_translate("Form", "unit13"))
        item = self.listWidget_32.item(13)
        item.setText(_translate("Form", "unit14"))
        item = self.listWidget_32.item(14)
        item.setText(_translate("Form", "unit15"))
        item = self.listWidget_32.item(15)
        item.setText(_translate("Form", "unit16"))
        item = self.listWidget_32.item(16)
        item.setText(_translate("Form", "unit17"))
        item = self.listWidget_32.item(17)
        item.setText(_translate("Form", "unit18"))
        item = self.listWidget_32.item(18)
        item.setText(_translate("Form", "unit19"))
        item = self.listWidget_32.item(19)
        item.setText(_translate("Form", "unit20"))
        item = self.listWidget_32.item(20)
        item.setText(_translate("Form", "unit21"))
        item = self.listWidget_32.item(21)
        item.setText(_translate("Form", "unit22"))
        item = self.listWidget_32.item(22)
        item.setText(_translate("Form", "unit23"))
        item = self.listWidget_32.item(23)
        item.setText(_translate("Form", "unit24"))
        item = self.listWidget_32.item(24)
        item.setText(_translate("Form", "unit25"))
        item = self.listWidget_32.item(25)
        item.setText(_translate("Form", "unit26"))
        item = self.listWidget_32.item(26)
        item.setText(_translate("Form", "unit27"))
        item = self.listWidget_32.item(27)
        item.setText(_translate("Form", "unit28"))
        self.listWidget_32.setSortingEnabled(__sortingEnabled)
        self.label_89.setText(_translate("Form", "单位名称："))
        self.lineEdit_49.setText(_translate("Form", "unit5"))
        self.label_80.setText(_translate("Form", "自退化度："))
        self.lineEdit_43.setText(_translate("Form", "0.6"))
        self.label_81.setText(_translate("Form", "突变率："))
        self.lineEdit_44.setText(_translate("Form", "0.0005"))
        self.label_82.setText(_translate("Form", "可视域："))
        self.lineEdit_45.setText(_translate("Form", "5"))
        self.label_83.setText(_translate("Form", "影响禀赋："))
        self.lineEdit_46.setText(_translate("Form", "17"))
        self.label_84.setText(_translate("Form", "决策策略："))
        self.lineEdit_47.setText(_translate("Form", "normal"))
        self.label_87.setText(_translate("Form", "所在处境："))
        self.lineEdit_48.setText(_translate("Form", "Position7"))
        self.label_106.setText(_translate("Form", "目标："))
        self.lineEdit_57.setText(_translate("Form", "Position767"))
        __sortingEnabled = self.listWidget_14.isSortingEnabled()
        self.listWidget_14.setSortingEnabled(False)
        item = self.listWidget_14.item(0)
        item.setText(_translate("Form", "advisor5"))
        item = self.listWidget_14.item(1)
        item.setText(_translate("Form", "advisor12"))
        item = self.listWidget_14.item(2)
        item.setText(_translate("Form", "advisor65"))
        item = self.listWidget_14.item(3)
        item.setText(_translate("Form", "advisor54"))
        item = self.listWidget_14.item(4)
        item.setText(_translate("Form", "advisor81"))
        item = self.listWidget_14.item(5)
        item.setText(_translate("Form", "advisor7"))
        item = self.listWidget_14.item(6)
        item.setText(_translate("Form", "advisor12"))
        item = self.listWidget_14.item(7)
        item.setText(_translate("Form", "advisor18"))
        item = self.listWidget_14.item(8)
        item.setText(_translate("Form", "advisor34"))
        self.listWidget_14.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_15.isSortingEnabled()
        self.listWidget_15.setSortingEnabled(False)
        item = self.listWidget_15.item(0)
        item.setText(_translate("Form", "Monitor16"))
        item = self.listWidget_15.item(1)
        item.setText(_translate("Form", "Monitor1"))
        item = self.listWidget_15.item(2)
        item.setText(_translate("Form", "Monitor6"))
        item = self.listWidget_15.item(3)
        item.setText(_translate("Form", "Monitor12"))
        item = self.listWidget_15.item(4)
        item.setText(_translate("Form", "Monitor15"))
        item = self.listWidget_15.item(5)
        item.setText(_translate("Form", "Monitor8"))
        self.listWidget_15.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_16.isSortingEnabled()
        self.listWidget_16.setSortingEnabled(False)
        item = self.listWidget_16.item(0)
        item.setText(_translate("Form", "unit0"))
        item = self.listWidget_16.item(1)
        item.setText(_translate("Form", "unit4"))
        item = self.listWidget_16.item(2)
        item.setText(_translate("Form", "unit9 "))
        self.listWidget_16.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.unitTab), _translate("Form", "仿真成员"))
        self.label_165.setText(_translate("Form", "建议者："))
        self.label_171.setText(_translate("Form", "连接单元："))
        __sortingEnabled = self.listWidget_24.isSortingEnabled()
        self.listWidget_24.setSortingEnabled(False)
        item = self.listWidget_24.item(0)
        item.setText(_translate("Form", "unit0"))
        item = self.listWidget_24.item(1)
        item.setText(_translate("Form", "unit4"))
        item = self.listWidget_24.item(2)
        item.setText(_translate("Form", "unit9 "))
        self.listWidget_24.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_22.isSortingEnabled()
        self.listWidget_22.setSortingEnabled(False)
        item = self.listWidget_22.item(0)
        item.setText(_translate("Form", "advisor5"))
        item = self.listWidget_22.item(1)
        item.setText(_translate("Form", "advisor12"))
        item = self.listWidget_22.item(2)
        item.setText(_translate("Form", "advisor65"))
        item = self.listWidget_22.item(3)
        item.setText(_translate("Form", "advisor54"))
        item = self.listWidget_22.item(4)
        item.setText(_translate("Form", "advisor81"))
        item = self.listWidget_22.item(5)
        item.setText(_translate("Form", "advisor7"))
        item = self.listWidget_22.item(6)
        item.setText(_translate("Form", "advisor12"))
        item = self.listWidget_22.item(7)
        item.setText(_translate("Form", "advisor18"))
        item = self.listWidget_22.item(8)
        item.setText(_translate("Form", "advisor34"))
        self.listWidget_22.setSortingEnabled(__sortingEnabled)
        self.label_175.setText(_translate("Form", "建议者名称："))
        self.lineEdit_95.setText(_translate("Form", "advisor5"))
        self.label_167.setText(_translate("Form", "突变率："))
        self.lineEdit_90.setText(_translate("Form", "0.0005"))
        self.label_169.setText(_translate("Form", "影响禀赋："))
        self.lineEdit_92.setText(_translate("Form", "17"))
        self.label_170.setText(_translate("Form", "决策策略："))
        self.lineEdit_93.setText(_translate("Form", "normal"))
        self.label_184.setText(_translate("Form", "禀赋剩余："))
        self.lineEdit_94.setText(_translate("Form", "4.6"))
        self.label_176.setText(_translate("Form", "连接单元名称："))
        self.lineEdit_96.setText(_translate("Form", "unit9"))
        self.label_174.setText(_translate("Form", "所处位置："))
        self.lineEdit_102.setText(_translate("Form", "position4"))
        self.label_181.setText(_translate("Form", "所给建议："))
        self.lineEdit_103.setText(_translate("Form", "a9"))
        self.label_172.setText(_translate("Form", "影响强度："))
        self.lineEdit_97.setText(_translate("Form", "4.5"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.advisorTab), _translate("Form", "建议者"))
        __sortingEnabled = self.listWidget_25.isSortingEnabled()
        self.listWidget_25.setSortingEnabled(False)
        item = self.listWidget_25.item(0)
        item.setText(_translate("Form", "unit0"))
        item = self.listWidget_25.item(1)
        item.setText(_translate("Form", "unit4"))
        item = self.listWidget_25.item(2)
        item.setText(_translate("Form", "unit9 "))
        self.listWidget_25.setSortingEnabled(__sortingEnabled)
        self.label_173.setText(_translate("Form", "连接单元："))
        self.label_105.setText(_translate("Form", "监控者："))
        __sortingEnabled = self.listWidget_17.isSortingEnabled()
        self.listWidget_17.setSortingEnabled(False)
        item = self.listWidget_17.item(0)
        item.setText(_translate("Form", "Monitor16"))
        item = self.listWidget_17.item(1)
        item.setText(_translate("Form", "Monitor1"))
        item = self.listWidget_17.item(2)
        item.setText(_translate("Form", "Monitor6"))
        item = self.listWidget_17.item(3)
        item.setText(_translate("Form", "Monitor12"))
        item = self.listWidget_17.item(4)
        item.setText(_translate("Form", "Monitor15"))
        item = self.listWidget_17.item(5)
        item.setText(_translate("Form", "Monitor8"))
        self.listWidget_17.setSortingEnabled(__sortingEnabled)
        self.label_177.setText(_translate("Form", "监控者名称："))
        self.lineEdit_98.setText(_translate("Form", "Monitor16"))
        self.label_178.setText(_translate("Form", "监控禀赋："))
        self.lineEdit_99.setText(_translate("Form", "19"))
        self.label_185.setText(_translate("Form", "禀赋剩余："))
        self.lineEdit_106.setText(_translate("Form", "4.6"))
        self.label_179.setText(_translate("Form", "连接单元名称："))
        self.lineEdit_100.setText(_translate("Form", "unit9"))
        self.label_182.setText(_translate("Form", "单元所在位置："))
        self.lineEdit_104.setText(_translate("Form", "position4"))
        self.label_183.setText(_translate("Form", "单元预动作："))
        self.lineEdit_105.setText(_translate("Form", "a8"))
        self.label_180.setText(_translate("Form", "监控强度："))
        self.lineEdit_101.setText(_translate("Form", "4.3"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.monitorTab), _translate("Form", "监控者"))

import GraphRes_rc
