# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coEvolution_child.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(903, 601)
        self.setting_frame = QtWidgets.QFrame(Form)
        self.setting_frame.setEnabled(True)
        self.setting_frame.setGeometry(QtCore.QRect(0, 0, 901, 271))
        self.setting_frame.setToolTipDuration(2)
        self.setting_frame.setStyleSheet("background-color: rgb(238, 255, 246);")
        self.setting_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_frame.setObjectName("setting_frame")
        self.simulation_message_label = QtWidgets.QLabel(self.setting_frame)
        self.simulation_message_label.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.simulation_message_label.setObjectName("simulation_message_label")
        self.layoutWidget = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 230, 861, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_icon=QtGui.QIcon(r'E:\code\PycharmProjects\simulation\UI\播放按钮.ico')
        self.pause_icon=QtGui.QIcon(r'E:\code\PycharmProjects\simulation\UI\暂停.ico')
        self.start_or_pause_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.start_or_pause_btn.setIcon(self.start_icon)
        self.start_or_pause_btn.setText("")
        self.start_or_pause_btn.setObjectName("start_or_pause_btn")
        self.horizontalLayout_4.addWidget(self.start_or_pause_btn)
        self.stop_icon=QtGui.QIcon(r'E:\code\PycharmProjects\simulation\UI\停止.ico')
        self.stop_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_btn.setIcon(self.stop_icon)
        self.stop_btn.setText("")
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_4.addWidget(self.stop_btn)
        self.progress_label = QtWidgets.QLabel(self.layoutWidget)
        self.progress_label.setObjectName("progress_label")
        self.horizontalLayout_4.addWidget(self.progress_label)
        self.exe_progress_bar = QtWidgets.QProgressBar(self.layoutWidget)
        self.exe_progress_bar.setProperty("value", 0)
        self.exe_progress_bar.setObjectName("exe_progress_bar")
        self.horizontalLayout_4.addWidget(self.exe_progress_bar)
        self.layoutWidget_2 = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 150, 861, 74))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.se_ID_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.se_ID_label.setObjectName("se_ID_label")
        self.gridLayout_2.addWidget(self.se_ID_label, 0, 0, 1, 1)
        self.se_ID_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.se_ID_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.se_ID_edit.setObjectName("se_ID_edit")
        self.gridLayout_2.addWidget(self.se_ID_edit, 0, 1, 1, 1)
        self.result_handle_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.result_handle_label.setObjectName("result_handle_label")
        self.gridLayout_2.addWidget(self.result_handle_label, 0, 2, 1, 1)
        self.result_handle_combobox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.result_handle_combobox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.result_handle_combobox.setObjectName("result_handle_combobox")
        self.result_handle_combobox.addItem("")
        self.result_handle_combobox.addItem("")
        self.gridLayout_2.addWidget(self.result_handle_combobox, 0, 3, 1, 1)
        self.version_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.version_label.setObjectName("version_label")
        self.gridLayout_2.addWidget(self.version_label, 1, 0, 1, 1)
        self.version_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.version_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.version_edit.setObjectName("version_edit")
        self.gridLayout_2.addWidget(self.version_edit, 1, 1, 1, 1)
        self.generation_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.generation_label.setObjectName("generation_label")
        self.gridLayout_2.addWidget(self.generation_label, 1, 2, 1, 1)
        self.modify_date_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.modify_date_label.setObjectName("modify_date_label")
        self.gridLayout_2.addWidget(self.modify_date_label, 2, 0, 1, 1)
        self.modify_dateEdit = QtWidgets.QDateEdit(self.layoutWidget_2)
        self.modify_dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.modify_dateEdit.setObjectName("modify_dateEdit")
        self.gridLayout_2.addWidget(self.modify_dateEdit, 2, 1, 1, 1)
        self.step_size_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.step_size_label.setObjectName("step_size_label")
        self.gridLayout_2.addWidget(self.step_size_label, 2, 2, 1, 1)
        self.step_size_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.step_size_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.step_size_lineEdit.setObjectName("step_size_lineEdit")
        self.gridLayout_2.addWidget(self.step_size_lineEdit, 2, 3, 1, 1)
        self.generation_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.generation_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.generation_lineEdit.setObjectName("generation_lineEdit")
        self.gridLayout_2.addWidget(self.generation_lineEdit, 1, 3, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 30, 861, 112))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.units_dir_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.units_dir_label.setObjectName("units_dir_label")
        self.gridLayout.addWidget(self.units_dir_label, 0, 0, 1, 1)
        self.units_dir_path = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.units_dir_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.units_dir_path.setText("")
        self.units_dir_path.setObjectName("units_dir_path")
        self.gridLayout.addWidget(self.units_dir_path, 0, 1, 1, 1)
        self.units_filedialog_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.units_filedialog_btn.setObjectName("units_filedialog_btn")
        self.gridLayout.addWidget(self.units_filedialog_btn, 0, 2, 1, 1)
        self.advisor_dir_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.advisor_dir_label.setObjectName("advisor_dir_label")
        self.gridLayout.addWidget(self.advisor_dir_label, 1, 0, 1, 1)
        self.advisor_dir_path = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.advisor_dir_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.advisor_dir_path.setText("")
        self.advisor_dir_path.setObjectName("advisor_dir_path")
        self.gridLayout.addWidget(self.advisor_dir_path, 1, 1, 1, 1)
        self.advisor_filedialog_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.advisor_filedialog_btn.setObjectName("advisor_filedialog_btn")
        self.gridLayout.addWidget(self.advisor_filedialog_btn, 1, 2, 1, 1)
        self.monitor_dir_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.monitor_dir_label.setObjectName("monitor_dir_label")
        self.gridLayout.addWidget(self.monitor_dir_label, 2, 0, 1, 1)
        self.monitor_dir_path = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.monitor_dir_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.monitor_dir_path.setText("")
        self.monitor_dir_path.setObjectName("monitor_dir_path")
        self.gridLayout.addWidget(self.monitor_dir_path, 2, 1, 1, 1)
        self.monitor_filedialog_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.monitor_filedialog_btn.setObjectName("monitor_filedialog_btn")
        self.gridLayout.addWidget(self.monitor_filedialog_btn, 2, 2, 1, 1)
        self.record_dir_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.record_dir_label.setObjectName("record_dir_label")
        self.gridLayout.addWidget(self.record_dir_label, 3, 0, 1, 1)
        self.record_dir_path = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.record_dir_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.record_dir_path.setObjectName("record_dir_path")
        self.gridLayout.addWidget(self.record_dir_path, 3, 1, 1, 1)
        self.record_filedialog_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.record_filedialog_btn.setObjectName("record_filedialog_btn")
        self.gridLayout.addWidget(self.record_filedialog_btn, 3, 2, 1, 1)
        self.log_frame = QtWidgets.QFrame(Form)
        self.log_frame.setGeometry(QtCore.QRect(0, 270, 901, 291))
        self.log_frame.setStyleSheet("background-color: rgb(255, 249, 244);")
        self.log_frame.setObjectName("log_frame")
        self.log_text = QtWidgets.QTextEdit(self.log_frame)
        self.log_text.setGeometry(QtCore.QRect(10, 10, 881, 261))
        self.log_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.log_text.setObjectName("log_text")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.simulation_message_label.setText(_translate("Form", "仿真信息："))
        self.start_or_pause_btn.setToolTip(_translate("Form", "<html><head/><body><p>开始</p></body></html>"))
        self.start_or_pause_btn.setWhatsThis(_translate("Form", "<html><head/><body><p>继续</p></body></html>"))
        self.stop_btn.setToolTip(_translate("Form", "<html><head/><body><p>终止</p></body></html>"))
        self.stop_btn.setWhatsThis(_translate("Form", "<html><head/><body><p>终止</p></body></html>"))
        self.progress_label.setText(_translate("Form", "仿真进度："))
        self.se_ID_label.setText(_translate("Form", "仿真执行ID："))
        self.se_ID_edit.setText(_translate("Form", "cE-ex01"))
        self.result_handle_label.setText(_translate("Form", "代间结果处理："))
        self.result_handle_combobox.setItemText(0, _translate("Form", "True"))
        self.result_handle_combobox.setItemText(1, _translate("Form", "False"))
        self.version_label.setText(_translate("Form", "版本号："))
        self.version_edit.setText(_translate("Form", "version-0.0"))
        self.generation_label.setText(_translate("Form", "仿真迭代数："))
        self.modify_date_label.setText(_translate("Form", "修改日期："))
        self.modify_dateEdit.setDisplayFormat(_translate("Form", "yyyy.MM.dd"))
        self.step_size_label.setText(_translate("Form", "仿真记录步长："))
        self.step_size_lineEdit.setText(_translate("Form", "50"))
        self.units_dir_label.setText(_translate("Form", "众进化原子型单元路径："))
        self.units_filedialog_btn.setText(_translate("Form", "浏览..."))
        self.advisor_dir_label.setText(_translate("Form", "众进化建议者单元路径："))
        self.advisor_filedialog_btn.setText(_translate("Form", "浏览..."))
        self.monitor_dir_label.setText(_translate("Form", "众进化监控者单元路径："))
        self.monitor_filedialog_btn.setText(_translate("Form", "浏览..."))
        self.record_dir_label.setText(_translate("Form", "结果记录文件夹路径："))
        self.record_filedialog_btn.setText(_translate("Form", "设置..."))
        self.log_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

