# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'informationPropagation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1201, 497)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 491))
        self.widget.setStyleSheet("background-color: rgb(224, 227, 255);")
        self.widget.setObjectName("widget")
        self.label_79 = QtWidgets.QLabel(self.widget)
        self.label_79.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label_79.setObjectName("label_79")
        self.listWidget_32 = QtWidgets.QListWidget(self.widget)
        self.listWidget_32.setGeometry(QtCore.QRect(80, 20, 161, 171))
        self.listWidget_32.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_32.setObjectName("listWidget_32")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_32.addItem(item)
        self.label_80 = QtWidgets.QLabel(self.widget)
        self.label_80.setGeometry(QtCore.QRect(270, 20, 61, 20))
        self.label_80.setObjectName("label_80")
        self.listWidget_33 = QtWidgets.QListWidget(self.widget)
        self.listWidget_33.setGeometry(QtCore.QRect(340, 20, 161, 171))
        self.listWidget_33.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.listWidget_33.setObjectName("listWidget_33")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_33.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_33.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_33.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_33.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_33.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_33.addItem(item)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(520, 220, 609, 191))
        self.widget_3.setStyleSheet("background-color: rgb(255, 254, 242);")
        self.widget_3.setObjectName("widget_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 91, 21))
        self.label_4.setObjectName("label_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_3)
        self.graphicsView.setGeometry(QtCore.QRect(10, 30, 591, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 231, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_106 = QtWidgets.QLabel(self.layoutWidget)
        self.label_106.setObjectName("label_106")
        self.gridLayout_2.addWidget(self.label_106, 5, 0, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_57.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_2.addWidget(self.lineEdit_57, 5, 1, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.layoutWidget)
        self.label_89.setObjectName("label_89")
        self.gridLayout_2.addWidget(self.label_89, 0, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.layoutWidget)
        self.label_82.setObjectName("label_82")
        self.gridLayout_2.addWidget(self.label_82, 1, 0, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_46.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_2.addWidget(self.lineEdit_46, 2, 1, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_49.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_2.addWidget(self.lineEdit_49, 0, 1, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_47.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_2.addWidget(self.lineEdit_47, 3, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.layoutWidget)
        self.label_85.setObjectName("label_85")
        self.gridLayout_2.addWidget(self.label_85, 3, 0, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.layoutWidget)
        self.label_84.setObjectName("label_84")
        self.gridLayout_2.addWidget(self.label_84, 2, 0, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_44.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_2.addWidget(self.lineEdit_44, 1, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.layoutWidget)
        self.label_87.setObjectName("label_87")
        self.gridLayout_2.addWidget(self.label_87, 4, 0, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_48.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_2.addWidget(self.lineEdit_48, 4, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(520, 20, 609, 191))
        self.widget_2.setStyleSheet("background-color: rgb(255, 254, 242);")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 91, 21))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 591, 151))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_79.setText(_translate("Form", "仿真成员："))
        __sortingEnabled = self.listWidget_32.isSortingEnabled()
        self.listWidget_32.setSortingEnabled(False)
        item = self.listWidget_32.item(0)
        item.setText(_translate("Form", "unit1"))
        item = self.listWidget_32.item(1)
        item.setText(_translate("Form", "unit2"))
        item = self.listWidget_32.item(2)
        item.setText(_translate("Form", "unit3"))
        item = self.listWidget_32.item(3)
        item.setText(_translate("Form", "unit4"))
        item = self.listWidget_32.item(4)
        item.setText(_translate("Form", "unit5"))
        item = self.listWidget_32.item(5)
        item.setText(_translate("Form", "unit6"))
        item = self.listWidget_32.item(6)
        item.setText(_translate("Form", "unit7"))
        item = self.listWidget_32.item(7)
        item.setText(_translate("Form", "unit8"))
        item = self.listWidget_32.item(8)
        item.setText(_translate("Form", "unit9"))
        item = self.listWidget_32.item(9)
        item.setText(_translate("Form", "unit10"))
        item = self.listWidget_32.item(10)
        item.setText(_translate("Form", "unit11"))
        item = self.listWidget_32.item(11)
        item.setText(_translate("Form", "unit12"))
        item = self.listWidget_32.item(12)
        item.setText(_translate("Form", "unit13"))
        item = self.listWidget_32.item(13)
        item.setText(_translate("Form", "unit14"))
        item = self.listWidget_32.item(14)
        item.setText(_translate("Form", "unit15"))
        item = self.listWidget_32.item(15)
        item.setText(_translate("Form", "unit16"))
        item = self.listWidget_32.item(16)
        item.setText(_translate("Form", "unit17"))
        item = self.listWidget_32.item(17)
        item.setText(_translate("Form", "unit18"))
        item = self.listWidget_32.item(18)
        item.setText(_translate("Form", "unit19"))
        item = self.listWidget_32.item(19)
        item.setText(_translate("Form", "unit20"))
        item = self.listWidget_32.item(20)
        item.setText(_translate("Form", "unit21"))
        item = self.listWidget_32.item(21)
        item.setText(_translate("Form", "unit22"))
        item = self.listWidget_32.item(22)
        item.setText(_translate("Form", "unit23"))
        item = self.listWidget_32.item(23)
        item.setText(_translate("Form", "unit24"))
        item = self.listWidget_32.item(24)
        item.setText(_translate("Form", "unit25"))
        item = self.listWidget_32.item(25)
        item.setText(_translate("Form", "unit26"))
        item = self.listWidget_32.item(26)
        item.setText(_translate("Form", "unit27"))
        item = self.listWidget_32.item(27)
        item.setText(_translate("Form", "unit28"))
        self.listWidget_32.setSortingEnabled(__sortingEnabled)
        self.label_80.setText(_translate("Form", "连接成员："))
        __sortingEnabled = self.listWidget_33.isSortingEnabled()
        self.listWidget_33.setSortingEnabled(False)
        item = self.listWidget_33.item(0)
        item.setText(_translate("Form", "unit2"))
        item = self.listWidget_33.item(1)
        item.setText(_translate("Form", "unit3"))
        item = self.listWidget_33.item(2)
        item.setText(_translate("Form", "unit5"))
        item = self.listWidget_33.item(3)
        item.setText(_translate("Form", "unit7"))
        item = self.listWidget_33.item(4)
        item.setText(_translate("Form", "unit15"))
        item = self.listWidget_33.item(5)
        item.setText(_translate("Form", "unit25"))
        self.listWidget_33.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("Form", "成员关系曲线"))
        self.label_106.setText(_translate("Form", "目标："))
        self.lineEdit_57.setText(_translate("Form", "Position767"))
        self.label_89.setText(_translate("Form", "单位名称："))
        self.label_82.setText(_translate("Form", "突变率："))
        self.lineEdit_46.setText(_translate("Form", "17"))
        self.lineEdit_49.setText(_translate("Form", "unit1"))
        self.lineEdit_47.setText(_translate("Form", "normal"))
        self.label_85.setText(_translate("Form", "决策策略："))
        self.label_84.setText(_translate("Form", "影响禀赋："))
        self.lineEdit_44.setText(_translate("Form", "0.0005"))
        self.label_87.setText(_translate("Form", "所在处境："))
        self.lineEdit_48.setText(_translate("Form", "Position7"))
        self.label.setText(_translate("Form", "成员动作信息"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

import GraphRes_rc
