# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_exe_monitor_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1199, 717)
        Form.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1200, 251))
        self.frame_2.setToolTipDuration(2)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_151 = QtWidgets.QLabel(self.frame_2)
        self.label_151.setGeometry(QtCore.QRect(90, 20, 121, 16))
        self.label_151.setObjectName("label_151")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget_7.setGeometry(QtCore.QRect(850, 40, 241, 141))
        self.tableWidget_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(2)
        self.tableWidget_7.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(1, 1, item)
        self.label_159 = QtWidgets.QLabel(self.frame_2)
        self.label_159.setGeometry(QtCore.QRect(900, 20, 141, 20))
        self.label_159.setObjectName("label_159")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(220, 200, 801, 22))
        self.horizontalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider.setProperty("value", 5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_160 = QtWidgets.QLabel(self.frame_2)
        self.label_160.setGeometry(QtCore.QRect(90, 200, 121, 20))
        self.label_160.setObjectName("label_160")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(1030, 200, 91, 16))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(602, 42, 232, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_86 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_86.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_86.setText("")
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.gridLayout_7.addWidget(self.lineEdit_86, 3, 1, 1, 1)
        self.label_157 = QtWidgets.QLabel(self.layoutWidget)
        self.label_157.setObjectName("label_157")
        self.gridLayout_7.addWidget(self.label_157, 1, 0, 1, 1)
        self.label_156 = QtWidgets.QLabel(self.layoutWidget)
        self.label_156.setObjectName("label_156")
        self.gridLayout_7.addWidget(self.label_156, 0, 0, 1, 1)
        self.lineEdit_88 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_88.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_88.setText("")
        self.lineEdit_88.setObjectName("lineEdit_88")
        self.gridLayout_7.addWidget(self.lineEdit_88, 2, 1, 1, 1)
        self.label_158 = QtWidgets.QLabel(self.layoutWidget)
        self.label_158.setObjectName("label_158")
        self.gridLayout_7.addWidget(self.label_158, 3, 0, 1, 1)
        self.label_164 = QtWidgets.QLabel(self.layoutWidget)
        self.label_164.setObjectName("label_164")
        self.gridLayout_7.addWidget(self.label_164, 2, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_9.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_7.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_7.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.label_161 = QtWidgets.QLabel(self.layoutWidget)
        self.label_161.setObjectName("label_161")
        self.gridLayout_7.addWidget(self.label_161, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_85 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_85.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_85.setText("")
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.horizontalLayout_5.addWidget(self.lineEdit_85)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(91, 41, 492, 138))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_154 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_154.setObjectName("label_154")
        self.horizontalLayout_8.addWidget(self.label_154)
        self.lineEdit_83 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_83.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_83.setText("")
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.horizontalLayout_8.addWidget(self.lineEdit_83)
        self.pushButton_46 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_8.addWidget(self.pushButton_46)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_150 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_150.setObjectName("label_150")
        self.gridLayout_10.addWidget(self.label_150, 0, 0, 1, 1)
        self.lineEdit_81 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_81.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_81.setText("")
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.gridLayout_10.addWidget(self.lineEdit_81, 0, 1, 1, 1)
        self.label_149 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_149.setObjectName("label_149")
        self.gridLayout_10.addWidget(self.label_149, 0, 2, 1, 1)
        self.lineEdit_127 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_127.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_127.setText("")
        self.lineEdit_127.setObjectName("lineEdit_127")
        self.gridLayout_10.addWidget(self.lineEdit_127, 0, 3, 1, 1)
        self.label_153 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_153.setObjectName("label_153")
        self.gridLayout_10.addWidget(self.label_153, 1, 0, 1, 1)
        self.lineEdit_82 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_82.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_82.setText("")
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.gridLayout_10.addWidget(self.lineEdit_82, 1, 1, 1, 1)
        self.label_155 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_155.setObjectName("label_155")
        self.gridLayout_10.addWidget(self.label_155, 1, 2, 1, 1)
        self.lineEdit_84 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_84.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_84.setText("")
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.gridLayout_10.addWidget(self.lineEdit_84, 1, 3, 1, 1)
        self.label_162 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_162.setObjectName("label_162")
        self.gridLayout_10.addWidget(self.label_162, 2, 0, 1, 1)
        self.lineEdit_87 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_87.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_87.setText("")
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.gridLayout_10.addWidget(self.lineEdit_87, 2, 1, 1, 1)
        self.label_163 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_163.setObjectName("label_163")
        self.gridLayout_10.addWidget(self.label_163, 2, 2, 1, 1)
        self.dateEdit_7 = QtWidgets.QDateEdit(self.layoutWidget_2)
        self.dateEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.dateEdit_7.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 11, 17), QtCore.QTime(0, 0, 0)))
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.gridLayout_10.addWidget(self.dateEdit_7, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_50 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_50.setStyleSheet("image: url(:/icon/快进.ico);")
        self.pushButton_50.setText("")
        self.pushButton_50.setObjectName("pushButton_50")
        self.horizontalLayout_3.addWidget(self.pushButton_50)
        self.pushButton_40 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_40.setStyleSheet("image: url(:/icon/播放按钮.ico);")
        self.pushButton_40.setText("")
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_3.addWidget(self.pushButton_40)
        self.pushButton_41 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_41.setStyleSheet("image: url(:/icon/暂停.ico);")
        self.pushButton_41.setText("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_3.addWidget(self.pushButton_41)
        self.pushButton_39 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_39.setStyleSheet("image: url(:/icon/停止.ico);")
        self.pushButton_39.setText("")
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_3.addWidget(self.pushButton_39)
        self.pushButton_38 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_38.setStyleSheet("image: url(:/icon/倒退.ico);")
        self.pushButton_38.setText("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_3.addWidget(self.pushButton_38)
        self.pushButton_35 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_35.setStyleSheet("image: url(:/icon/下一个.ico);")
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_3.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_36.setStyleSheet("image: url(:/icon/取消.ico);")
        self.pushButton_36.setText("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_3.addWidget(self.pushButton_36)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(0, 250, 401, 491))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.label_165 = QtWidgets.QLabel(self.widget_2)
        self.label_165.setGeometry(QtCore.QRect(20, 20, 141, 20))
        self.label_165.setObjectName("label_165")
        self.comboBox_9 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_9.setGeometry(QtCore.QRect(90, 60, 131, 22))
        self.comboBox_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.comboBox_9.setObjectName("comboBox_9")
        self.textEdit_4 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 90, 381, 281))
        self.textEdit_4.setStyleSheet("")
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_51 = QtWidgets.QLabel(self.widget_2)
        self.label_51.setGeometry(QtCore.QRect(230, 60, 121, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.widget_2)
        self.label_52.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_52.setObjectName("label_52")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(350, 60, 31, 20))
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.tabWidget_3 = QtWidgets.QTabWidget(Form)
        self.tabWidget_3.setGeometry(QtCore.QRect(400, 250, 801, 511))
        self.tabWidget_3.setStyleSheet("")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.unitTab_2 = QtWidgets.QWidget()
        self.unitTab_2.setObjectName("unitTab_2")
        self.widget_3 = QtWidgets.QWidget(self.unitTab_2)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 791, 461))
        self.widget_3.setObjectName("widget_3")
        self.label_50 = QtWidgets.QLabel(self.widget_3)
        self.label_50.setGeometry(QtCore.QRect(530, 40, 111, 16))
        self.label_50.setObjectName("label_50")
        self.graphicsView_20 = QtWidgets.QGraphicsView(self.widget_3)
        self.graphicsView_20.setGeometry(QtCore.QRect(530, 60, 256, 161))
        self.graphicsView_20.setStyleSheet("")
        self.graphicsView_20.setObjectName("graphicsView_20")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 40, 501, 181))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_107 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_107.setObjectName("label_107")
        self.gridLayout_3.addWidget(self.label_107, 0, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_3.addWidget(self.comboBox_5, 0, 1, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_118.setObjectName("label_118")
        self.gridLayout_3.addWidget(self.label_118, 0, 2, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_65.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_65.setText("")
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout_3.addWidget(self.lineEdit_65, 0, 3, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_113.setObjectName("label_113")
        self.gridLayout_3.addWidget(self.label_113, 1, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_3.addWidget(self.comboBox_7, 1, 1, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_110.setObjectName("label_110")
        self.gridLayout_3.addWidget(self.label_110, 1, 2, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_60.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_60.setText("")
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout_3.addWidget(self.lineEdit_60, 1, 3, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_114.setObjectName("label_114")
        self.gridLayout_3.addWidget(self.label_114, 2, 0, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.comboBox_17.setObjectName("comboBox_17")
        self.gridLayout_3.addWidget(self.comboBox_17, 2, 1, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_111.setObjectName("label_111")
        self.gridLayout_3.addWidget(self.label_111, 2, 2, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_61.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_61.setText("")
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout_3.addWidget(self.lineEdit_61, 2, 3, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_117.setObjectName("label_117")
        self.gridLayout_3.addWidget(self.label_117, 3, 0, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_3.addWidget(self.comboBox_8, 3, 1, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_112.setObjectName("label_112")
        self.gridLayout_3.addWidget(self.label_112, 3, 2, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_62.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_62.setText("")
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout_3.addWidget(self.lineEdit_62, 3, 3, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_108.setObjectName("label_108")
        self.gridLayout_3.addWidget(self.label_108, 4, 0, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_58.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_58.setText("")
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_3.addWidget(self.lineEdit_58, 4, 1, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_115.setObjectName("label_115")
        self.gridLayout_3.addWidget(self.label_115, 4, 2, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_63.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_63.setText("")
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout_3.addWidget(self.lineEdit_63, 4, 3, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_109.setObjectName("label_109")
        self.gridLayout_3.addWidget(self.label_109, 5, 0, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_59.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_59.setText("")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_3.addWidget(self.lineEdit_59, 5, 1, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_119.setObjectName("label_119")
        self.gridLayout_3.addWidget(self.label_119, 5, 2, 1, 1)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_66.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_66.setText("")
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.gridLayout_3.addWidget(self.lineEdit_66, 5, 3, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 250, 782, 171))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 0, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 0, 2, 1, 1)
        self.graphicsView_17 = QtWidgets.QGraphicsView(self.layoutWidget_4)
        self.graphicsView_17.setStyleSheet("")
        self.graphicsView_17.setObjectName("graphicsView_17")
        self.gridLayout_5.addWidget(self.graphicsView_17, 1, 0, 1, 1)
        self.graphicsView_18 = QtWidgets.QGraphicsView(self.layoutWidget_4)
        self.graphicsView_18.setStyleSheet("")
        self.graphicsView_18.setObjectName("graphicsView_18")
        self.gridLayout_5.addWidget(self.graphicsView_18, 1, 1, 1, 1)
        self.graphicsView_19 = QtWidgets.QGraphicsView(self.layoutWidget_4)
        self.graphicsView_19.setStyleSheet("")
        self.graphicsView_19.setObjectName("graphicsView_19")
        self.gridLayout_5.addWidget(self.graphicsView_19, 1, 2, 1, 1)
        self.tabWidget_3.addTab(self.unitTab_2, "")
        self.advisorTab_2 = QtWidgets.QWidget()
        self.advisorTab_2.setObjectName("advisorTab_2")
        self.widget_4 = QtWidgets.QWidget(self.advisorTab_2)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 1200, 461))
        self.widget_4.setObjectName("widget_4")
        self.graphicsView_24 = QtWidgets.QGraphicsView(self.widget_4)
        self.graphicsView_24.setGeometry(QtCore.QRect(270, 260, 256, 192))
        self.graphicsView_24.setStyleSheet("border-image: url(:/patterns/5.png);")
        self.graphicsView_24.setObjectName("graphicsView_24")
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.widget_4)
        self.graphicsView_9.setGeometry(QtCore.QRect(10, 260, 256, 192))
        self.graphicsView_9.setStyleSheet("border-image: url(:/chart/10.png);")
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.widget_4)
        self.graphicsView_7.setGeometry(QtCore.QRect(500, 40, 281, 192))
        self.graphicsView_7.setStyleSheet("border-image: url(:/chart/7.png);")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.widget_4)
        self.graphicsView_8.setGeometry(QtCore.QRect(530, 260, 256, 192))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.layoutWidget_5 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 40, 471, 161))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_166 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_166.setObjectName("label_166")
        self.gridLayout_4.addWidget(self.label_166, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.label_188 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_188.setObjectName("label_188")
        self.gridLayout_4.addWidget(self.label_188, 0, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.comboBox_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_6, 0, 3, 1, 1)
        self.label_189 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_189.setObjectName("label_189")
        self.gridLayout_4.addWidget(self.label_189, 1, 0, 1, 1)
        self.lineEdit_109 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_109.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_109.setObjectName("lineEdit_109")
        self.gridLayout_4.addWidget(self.lineEdit_109, 1, 1, 1, 1)
        self.label_190 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_190.setObjectName("label_190")
        self.gridLayout_4.addWidget(self.label_190, 1, 2, 1, 1)
        self.lineEdit_110 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_110.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_110.setObjectName("lineEdit_110")
        self.gridLayout_4.addWidget(self.lineEdit_110, 1, 3, 1, 1)
        self.label_186 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_186.setObjectName("label_186")
        self.gridLayout_4.addWidget(self.label_186, 2, 0, 1, 1)
        self.lineEdit_107 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_107.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_107.setObjectName("lineEdit_107")
        self.gridLayout_4.addWidget(self.lineEdit_107, 2, 1, 1, 1)
        self.label_192 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_192.setObjectName("label_192")
        self.gridLayout_4.addWidget(self.label_192, 2, 2, 1, 1)
        self.lineEdit_112 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_112.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_112.setObjectName("lineEdit_112")
        self.gridLayout_4.addWidget(self.lineEdit_112, 2, 3, 1, 1)
        self.label_187 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_187.setObjectName("label_187")
        self.gridLayout_4.addWidget(self.label_187, 3, 0, 1, 1)
        self.lineEdit_108 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_108.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_108.setObjectName("lineEdit_108")
        self.gridLayout_4.addWidget(self.lineEdit_108, 3, 1, 1, 1)
        self.label_193 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_193.setObjectName("label_193")
        self.gridLayout_4.addWidget(self.label_193, 3, 2, 1, 1)
        self.lineEdit_113 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_113.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_113.setObjectName("lineEdit_113")
        self.gridLayout_4.addWidget(self.lineEdit_113, 3, 3, 1, 1)
        self.label_204 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_204.setObjectName("label_204")
        self.gridLayout_4.addWidget(self.label_204, 4, 0, 1, 1)
        self.lineEdit_123 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_123.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_123.setObjectName("lineEdit_123")
        self.gridLayout_4.addWidget(self.lineEdit_123, 4, 1, 1, 1)
        self.label_191 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_191.setObjectName("label_191")
        self.gridLayout_4.addWidget(self.label_191, 4, 2, 1, 1)
        self.lineEdit_111 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_111.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_111.setObjectName("lineEdit_111")
        self.gridLayout_4.addWidget(self.lineEdit_111, 4, 3, 1, 1)
        self.tabWidget_3.addTab(self.advisorTab_2, "")
        self.monitorTab_2 = QtWidgets.QWidget()
        self.monitorTab_2.setObjectName("monitorTab_2")
        self.label_120 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_120.setGeometry(QtCore.QRect(20, 30, 91, 20))
        self.label_120.setObjectName("label_120")
        self.label_195 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_195.setGeometry(QtCore.QRect(10, 60, 91, 20))
        self.label_195.setObjectName("label_195")
        self.lineEdit_115 = QtWidgets.QLineEdit(self.monitorTab_2)
        self.lineEdit_115.setGeometry(QtCore.QRect(160, 90, 71, 20))
        self.lineEdit_115.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_115.setObjectName("lineEdit_115")
        self.label_196 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_196.setGeometry(QtCore.QRect(10, 90, 91, 20))
        self.label_196.setObjectName("label_196")
        self.label_197 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_197.setGeometry(QtCore.QRect(20, 120, 131, 20))
        self.label_197.setObjectName("label_197")
        self.lineEdit_116 = QtWidgets.QLineEdit(self.monitorTab_2)
        self.lineEdit_116.setGeometry(QtCore.QRect(160, 120, 71, 20))
        self.lineEdit_116.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_116.setObjectName("lineEdit_116")
        self.label_198 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_198.setGeometry(QtCore.QRect(250, 30, 111, 20))
        self.label_198.setObjectName("label_198")
        self.lineEdit_117 = QtWidgets.QLineEdit(self.monitorTab_2)
        self.lineEdit_117.setGeometry(QtCore.QRect(400, 30, 71, 20))
        self.lineEdit_117.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_117.setObjectName("lineEdit_117")
        self.label_199 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_199.setGeometry(QtCore.QRect(260, 120, 141, 20))
        self.label_199.setObjectName("label_199")
        self.lineEdit_118 = QtWidgets.QLineEdit(self.monitorTab_2)
        self.lineEdit_118.setGeometry(QtCore.QRect(400, 120, 71, 20))
        self.lineEdit_118.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_118.setObjectName("lineEdit_118")
        self.lineEdit_119 = QtWidgets.QLineEdit(self.monitorTab_2)
        self.lineEdit_119.setGeometry(QtCore.QRect(400, 60, 71, 20))
        self.lineEdit_119.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_119.setObjectName("lineEdit_119")
        self.label_200 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_200.setGeometry(QtCore.QRect(250, 60, 101, 20))
        self.label_200.setObjectName("label_200")
        self.lineEdit_120 = QtWidgets.QLineEdit(self.monitorTab_2)
        self.lineEdit_120.setGeometry(QtCore.QRect(400, 90, 71, 20))
        self.lineEdit_120.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_120.setObjectName("lineEdit_120")
        self.label_201 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_201.setGeometry(QtCore.QRect(260, 90, 121, 20))
        self.label_201.setObjectName("label_201")
        self.label_203 = QtWidgets.QLabel(self.monitorTab_2)
        self.label_203.setGeometry(QtCore.QRect(250, 150, 131, 20))
        self.label_203.setObjectName("label_203")
        self.lineEdit_122 = QtWidgets.QLineEdit(self.monitorTab_2)
        self.lineEdit_122.setGeometry(QtCore.QRect(400, 150, 71, 20))
        self.lineEdit_122.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_122.setObjectName("lineEdit_122")
        self.comboBox_16 = QtWidgets.QComboBox(self.monitorTab_2)
        self.comboBox_16.setGeometry(QtCore.QRect(160, 30, 61, 21))
        self.comboBox_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.monitorTab_2)
        self.comboBox_3.setGeometry(QtCore.QRect(158, 60, 71, 22))
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.graphicsView_25 = QtWidgets.QGraphicsView(self.monitorTab_2)
        self.graphicsView_25.setGeometry(QtCore.QRect(270, 250, 256, 192))
        self.graphicsView_25.setStyleSheet("border-image: url(:/patterns/6.png);")
        self.graphicsView_25.setObjectName("graphicsView_25")
        self.graphicsView_11 = QtWidgets.QGraphicsView(self.monitorTab_2)
        self.graphicsView_11.setGeometry(QtCore.QRect(520, 30, 256, 192))
        self.graphicsView_11.setStyleSheet("border-image: url(:/chart/8.png);\n"
"")
        self.graphicsView_11.setObjectName("graphicsView_11")
        self.graphicsView_12 = QtWidgets.QGraphicsView(self.monitorTab_2)
        self.graphicsView_12.setGeometry(QtCore.QRect(0, 250, 256, 192))
        self.graphicsView_12.setStyleSheet("border-image: url(:/chart/9.png);")
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.textEdit_2 = QtWidgets.QTextEdit(self.monitorTab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(530, 250, 256, 192))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget_3.addTab(self.monitorTab_2, "")

        self.retranslateUi(Form)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_151.setText(_translate("Form", "Simulation message:"))
        item = self.tableWidget_7.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_7.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_7.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_7.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Attribute name"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Attribute value"))
        __sortingEnabled = self.tableWidget_7.isSortingEnabled()
        self.tableWidget_7.setSortingEnabled(False)
        self.tableWidget_7.setSortingEnabled(__sortingEnabled)
        self.label_159.setText(_translate("Form", "Global Attribute Table"))
        self.label_160.setText(_translate("Form", "Simulation progess:"))
        self.label.setText(_translate("Form", "Generation 0"))
        self.label_157.setText(_translate("Form", "Ending way:"))
        self.label_156.setText(_translate("Form", "Inherit setting::"))
        self.label_158.setText(_translate("Form", "Step size:"))
        self.label_164.setText(_translate("Form", "Operator:"))
        self.label_161.setText(_translate("Form", "Generation goto:"))
        self.pushButton_3.setText(_translate("Form", "Goto"))
        self.label_154.setText(_translate("Form", "Record path:"))
        self.pushButton_46.setText(_translate("Form", "Browe..."))
        self.label_150.setText(_translate("Form", "Execution ID:"))
        self.label_149.setText(_translate("Form", "Execution type:"))
        self.label_153.setText(_translate("Form", "Executdion MetaID:"))
        self.label_155.setText(_translate("Form", "Record Meta ID:"))
        self.label_162.setText(_translate("Form", "Version:"))
        self.label_163.setText(_translate("Form", "Modify date:"))
        self.dateEdit_7.setDisplayFormat(_translate("Form", "yyyy.MM.dd"))
        self.pushButton_50.setToolTip(_translate("Form", "<html><head/><body><p>跳转</p></body></html>"))
        self.pushButton_50.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_40.setToolTip(_translate("Form", "<html><head/><body><p>继续</p></body></html>"))
        self.pushButton_40.setWhatsThis(_translate("Form", "<html><head/><body><p>继续</p></body></html>"))
        self.pushButton_41.setToolTip(_translate("Form", "<html><head/><body><p>暂停</p></body></html>"))
        self.pushButton_41.setWhatsThis(_translate("Form", "<html><head/><body><p>暂停</p></body></html>"))
        self.pushButton_39.setToolTip(_translate("Form", "<html><head/><body><p>终止</p></body></html>"))
        self.pushButton_39.setWhatsThis(_translate("Form", "<html><head/><body><p>终止</p></body></html>"))
        self.pushButton_38.setToolTip(_translate("Form", "<html><head/><body><p>上一步</p></body></html>"))
        self.pushButton_38.setWhatsThis(_translate("Form", "<html><head/><body><p>前一步</p></body></html>"))
        self.pushButton_35.setToolTip(_translate("Form", "<html><head/><body><p>下一步</p></body></html>"))
        self.pushButton_35.setWhatsThis(_translate("Form", "<html><head/><body><p>后一步</p></body></html>"))
        self.pushButton_36.setToolTip(_translate("Form", "<html><head/><body><p>断点</p></body></html>"))
        self.pushButton_36.setWhatsThis(_translate("Form", "<html><head/><body><p>设置断点</p></body></html>"))
        self.label_165.setText(_translate("Form", "Global Attribute Chart:"))
        self.label_51.setText(_translate("Form", "Current Generation:"))
        self.label_52.setText(_translate("Form", "Attribute:"))
        self.label_50.setText(_translate("Form", "Earning:"))
        self.label_107.setText(_translate("Form", "unit\'s ID:"))
        self.label_118.setText(_translate("Form", "Unit\'s name:"))
        self.label_113.setText(_translate("Form", "Advisors:"))
        self.label_110.setText(_translate("Form", "Visual size:"))
        self.label_114.setText(_translate("Form", "Monitors:"))
        self.label_111.setText(_translate("Form", "Affected endowment:"))
        self.label_117.setText(_translate("Form", "Conn cE_units:"))
        self.label_112.setText(_translate("Form", "Decision strategy:"))
        self.label_108.setText(_translate("Form", "Self Degeneration:"))
        self.label_115.setText(_translate("Form", "Position sequence:"))
        self.label_109.setText(_translate("Form", "Mutation rate:"))
        self.label_119.setText(_translate("Form", "Target:"))
        self.label_47.setText(_translate("Form", "Conn unit\'s weight:"))
        self.label_48.setText(_translate("Form", "Position sequence:"))
        self.label_49.setText(_translate("Form", "Affected Coefficient:"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.unitTab_2), _translate("Form", "Units"))
        self.label_166.setText(_translate("Form", "Advisor\'s ID:"))
        self.comboBox_4.setItemText(0, _translate("Form", "a-00"))
        self.comboBox_4.setItemText(1, _translate("Form", "a-01"))
        self.comboBox_4.setItemText(2, _translate("Form", "a-02"))
        self.comboBox_4.setItemText(3, _translate("Form", "a-03"))
        self.comboBox_4.setItemText(4, _translate("Form", "a-04"))
        self.comboBox_4.setItemText(5, _translate("Form", "a-05"))
        self.comboBox_4.setItemText(6, _translate("Form", "a-06"))
        self.comboBox_4.setItemText(7, _translate("Form", "a-07"))
        self.comboBox_4.setItemText(8, _translate("Form", "a-08"))
        self.comboBox_4.setItemText(9, _translate("Form", "a-09"))
        self.comboBox_4.setItemText(10, _translate("Form", "a-10"))
        self.comboBox_4.setItemText(11, _translate("Form", "a-11"))
        self.comboBox_4.setItemText(12, _translate("Form", "a-12"))
        self.comboBox_4.setItemText(13, _translate("Form", "a-13"))
        self.comboBox_4.setItemText(14, _translate("Form", "a-14"))
        self.comboBox_4.setItemText(15, _translate("Form", "a-15"))
        self.comboBox_4.setItemText(16, _translate("Form", "a-16"))
        self.comboBox_4.setItemText(17, _translate("Form", "a-17"))
        self.comboBox_4.setItemText(18, _translate("Form", "a-18"))
        self.comboBox_4.setItemText(19, _translate("Form", "a-19"))
        self.label_188.setText(_translate("Form", "Conn unit\'s ID:"))
        self.comboBox_6.setItemText(0, _translate("Form", "u-00"))
        self.comboBox_6.setItemText(1, _translate("Form", "u-04"))
        self.comboBox_6.setItemText(2, _translate("Form", "u-09"))
        self.comboBox_6.setItemText(3, _translate("Form", "u-15"))
        self.comboBox_6.setItemText(4, _translate("Form", "u-18"))
        self.label_189.setText(_translate("Form", "Advisor\'s name:"))
        self.lineEdit_109.setText(_translate("Form", "advisor5"))
        self.label_190.setText(_translate("Form", "Conn unit\'s name:"))
        self.lineEdit_110.setText(_translate("Form", "unit9"))
        self.label_186.setText(_translate("Form", "Effection endowment:"))
        self.lineEdit_107.setText(_translate("Form", "17"))
        self.label_192.setText(_translate("Form", "Current position:"))
        self.lineEdit_112.setText(_translate("Form", "position4"))
        self.label_187.setText(_translate("Form", "Suggection Strategy:"))
        self.lineEdit_108.setText(_translate("Form", "normal"))
        self.label_193.setText(_translate("Form", "The suggestion:"))
        self.lineEdit_113.setText(_translate("Form", "a9"))
        self.label_204.setText(_translate("Form", "Influence result:"))
        self.lineEdit_123.setText(_translate("Form", "Accept"))
        self.label_191.setText(_translate("Form", "Sug coefficient:"))
        self.lineEdit_111.setText(_translate("Form", "4.5"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.advisorTab_2), _translate("Form", "Advisors"))
        self.label_120.setText(_translate("Form", "Monitor\'s ID:"))
        self.label_195.setText(_translate("Form", "Conn unit\'s ID:"))
        self.lineEdit_115.setText(_translate("Form", "Monitor16"))
        self.label_196.setText(_translate("Form", "Monitor\'s name:"))
        self.label_197.setText(_translate("Form", "Monitoring endowment:"))
        self.lineEdit_116.setText(_translate("Form", "19"))
        self.label_198.setText(_translate("Form", "Conn unit\'s name:"))
        self.lineEdit_117.setText(_translate("Form", "unit9"))
        self.label_199.setText(_translate("Form", "Monitoring coefficient:"))
        self.lineEdit_118.setText(_translate("Form", "4.3"))
        self.lineEdit_119.setText(_translate("Form", "position4"))
        self.label_200.setText(_translate("Form", "Current Position:"))
        self.lineEdit_120.setText(_translate("Form", "a8"))
        self.label_201.setText(_translate("Form", "unit\'s beforehand:"))
        self.label_203.setText(_translate("Form", "Monitoring result:"))
        self.lineEdit_122.setText(_translate("Form", "Succeed"))
        self.comboBox_16.setItemText(0, _translate("Form", "m-00"))
        self.comboBox_16.setItemText(1, _translate("Form", "m-01"))
        self.comboBox_16.setItemText(2, _translate("Form", "m-02"))
        self.comboBox_16.setItemText(3, _translate("Form", "m-03"))
        self.comboBox_16.setItemText(4, _translate("Form", "m-04"))
        self.comboBox_16.setItemText(5, _translate("Form", "m-05"))
        self.comboBox_16.setItemText(6, _translate("Form", "m-06"))
        self.comboBox_16.setItemText(7, _translate("Form", "m-07"))
        self.comboBox_16.setItemText(8, _translate("Form", "m-08"))
        self.comboBox_16.setItemText(9, _translate("Form", "m-09"))
        self.comboBox_16.setItemText(10, _translate("Form", "m-10"))
        self.comboBox_16.setItemText(11, _translate("Form", "m-11"))
        self.comboBox_16.setItemText(12, _translate("Form", "m-12"))
        self.comboBox_16.setItemText(13, _translate("Form", "m-13"))
        self.comboBox_16.setItemText(14, _translate("Form", "m-14"))
        self.comboBox_16.setItemText(15, _translate("Form", "m-15"))
        self.comboBox_16.setItemText(16, _translate("Form", "m-16"))
        self.comboBox_16.setItemText(17, _translate("Form", "m-17"))
        self.comboBox_16.setItemText(18, _translate("Form", "m-18"))
        self.comboBox_16.setItemText(19, _translate("Form", "m-19"))
        self.comboBox_3.setItemText(0, _translate("Form", "u-00"))
        self.comboBox_3.setItemText(1, _translate("Form", "u-04"))
        self.comboBox_3.setItemText(2, _translate("Form", "u-09"))
        self.comboBox_3.setItemText(3, _translate("Form", "u-15"))
        self.comboBox_3.setItemText(4, _translate("Form", "u-18"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.monitorTab_2), _translate("Form", "Monitors"))

import UI.GraphRes_rc
