# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_exe_Form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(918, 571)
        self.setting_frame = QtWidgets.QFrame(Form)
        self.setting_frame.setEnabled(True)
        self.setting_frame.setGeometry(QtCore.QRect(10, 0, 901, 561))
        self.setting_frame.setToolTipDuration(2)
        self.setting_frame.setStyleSheet("")
        self.setting_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_frame.setObjectName("setting_frame")
        self.simulation_message_label = QtWidgets.QLabel(self.setting_frame)
        self.simulation_message_label.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.simulation_message_label.setObjectName("simulation_message_label")
        self.layoutWidget_2 = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 260, 861, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_or_pause_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.start_or_pause_btn.setStyleSheet("image: url(:/icon/播放按钮.ico);")
        self.start_or_pause_btn.setText("")
        self.start_or_pause_btn.setObjectName("start_or_pause_btn")
        self.horizontalLayout_4.addWidget(self.start_or_pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.stop_btn.setStyleSheet("image: url(:/icon/停止.ico);")
        self.stop_btn.setText("")
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_4.addWidget(self.stop_btn)
        self.progress_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.progress_label.setObjectName("progress_label")
        self.horizontalLayout_4.addWidget(self.progress_label)
        self.exe_progress_bar = QtWidgets.QProgressBar(self.layoutWidget_2)
        self.exe_progress_bar.setProperty("value", 0)
        self.exe_progress_bar.setObjectName("exe_progress_bar")
        self.horizontalLayout_4.addWidget(self.exe_progress_bar)
        self.member_tableWidget = QtWidgets.QTableWidget(self.setting_frame)
        self.member_tableWidget.setGeometry(QtCore.QRect(20, 30, 241, 221))
        self.member_tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.member_tableWidget.setObjectName("member_tableWidget")
        self.member_tableWidget.setColumnCount(2)
        self.member_tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_tableWidget.setItem(10, 1, item)
        self.layoutWidget_3 = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 290, 861, 251))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.log_text_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.log_text_label.setObjectName("log_text_label")
        self.gridLayout_6.addWidget(self.log_text_label, 0, 0, 1, 1)
        self.warning_text_log_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.warning_text_log_label.setObjectName("warning_text_log_label")
        self.gridLayout_6.addWidget(self.warning_text_log_label, 0, 1, 1, 1)
        self.service_msg_log_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.service_msg_log_label.setObjectName("service_msg_log_label")
        self.gridLayout_6.addWidget(self.service_msg_log_label, 0, 2, 1, 1)
        self.log_text = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.log_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.log_text.setObjectName("log_text")
        self.gridLayout_6.addWidget(self.log_text, 1, 0, 1, 1)
        self.warning_log_text = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.warning_log_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.warning_log_text.setObjectName("warning_log_text")
        self.gridLayout_6.addWidget(self.warning_log_text, 1, 1, 1, 1)
        self.service_msg_log_text = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.service_msg_log_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.service_msg_log_text.setObjectName("service_msg_log_text")
        self.gridLayout_6.addWidget(self.service_msg_log_text, 1, 2, 1, 1)
        self.layoutWidget_6 = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(270, 32, 611, 83))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.member_xml_path_label = QtWidgets.QLabel(self.layoutWidget_6)
        self.member_xml_path_label.setObjectName("member_xml_path_label")
        self.gridLayout.addWidget(self.member_xml_path_label, 0, 0, 1, 1)
        self.members_xml_path_edit = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.members_xml_path_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.members_xml_path_edit.setText("")
        self.members_xml_path_edit.setObjectName("members_xml_path_edit")
        self.gridLayout.addWidget(self.members_xml_path_edit, 0, 1, 1, 1)
        self.members_filedialog_btn = QtWidgets.QPushButton(self.layoutWidget_6)
        self.members_filedialog_btn.setObjectName("members_filedialog_btn")
        self.gridLayout.addWidget(self.members_filedialog_btn, 0, 2, 1, 1)
        self.def_xml_path_label = QtWidgets.QLabel(self.layoutWidget_6)
        self.def_xml_path_label.setObjectName("def_xml_path_label")
        self.gridLayout.addWidget(self.def_xml_path_label, 1, 0, 1, 1)
        self.def_xml_path_edit = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.def_xml_path_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.def_xml_path_edit.setText("")
        self.def_xml_path_edit.setObjectName("def_xml_path_edit")
        self.gridLayout.addWidget(self.def_xml_path_edit, 1, 1, 1, 1)
        self.def_xml_filedialog_btn = QtWidgets.QPushButton(self.layoutWidget_6)
        self.def_xml_filedialog_btn.setObjectName("def_xml_filedialog_btn")
        self.gridLayout.addWidget(self.def_xml_filedialog_btn, 1, 2, 1, 1)
        self.record_dir_label = QtWidgets.QLabel(self.layoutWidget_6)
        self.record_dir_label.setObjectName("record_dir_label")
        self.gridLayout.addWidget(self.record_dir_label, 2, 0, 1, 1)
        self.record_dir_path_edit = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.record_dir_path_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.record_dir_path_edit.setText("")
        self.record_dir_path_edit.setObjectName("record_dir_path_edit")
        self.gridLayout.addWidget(self.record_dir_path_edit, 2, 1, 1, 1)
        self.record_filedialog_btn = QtWidgets.QPushButton(self.layoutWidget_6)
        self.record_filedialog_btn.setObjectName("record_filedialog_btn")
        self.gridLayout.addWidget(self.record_filedialog_btn, 2, 2, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(268, 230, 611, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.primitive_num_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.primitive_num_edit.setEnabled(False)
        self.primitive_num_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.primitive_num_edit.setText("")
        self.primitive_num_edit.setObjectName("primitive_num_edit")
        self.horizontalLayout.addWidget(self.primitive_num_edit)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.adviser_num_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.adviser_num_edit.setEnabled(False)
        self.adviser_num_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.adviser_num_edit.setText("")
        self.adviser_num_edit.setObjectName("adviser_num_edit")
        self.horizontalLayout.addWidget(self.adviser_num_edit)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.monitor_num_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.monitor_num_edit.setEnabled(False)
        self.monitor_num_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.monitor_num_edit.setText("")
        self.monitor_num_edit.setObjectName("monitor_num_edit")
        self.horizontalLayout.addWidget(self.monitor_num_edit)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.collective_num_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.collective_num_edit.setEnabled(False)
        self.collective_num_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.collective_num_edit.setText("")
        self.collective_num_edit.setObjectName("collective_num_edit")
        self.horizontalLayout.addWidget(self.collective_num_edit)
        self.layoutWidget1 = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(270, 120, 281, 98))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.se_ID_label = QtWidgets.QLabel(self.layoutWidget1)
        self.se_ID_label.setObjectName("se_ID_label")
        self.gridLayout_2.addWidget(self.se_ID_label, 0, 0, 1, 1)
        self.se_ID_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.se_ID_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.se_ID_edit.setText("")
        self.se_ID_edit.setObjectName("se_ID_edit")
        self.gridLayout_2.addWidget(self.se_ID_edit, 0, 1, 1, 1)
        self.se_ID_label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.se_ID_label_2.setObjectName("se_ID_label_2")
        self.gridLayout_2.addWidget(self.se_ID_label_2, 1, 0, 1, 1)
        self.meta_member_ID_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.meta_member_ID_edit.setEnabled(False)
        self.meta_member_ID_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.meta_member_ID_edit.setText("")
        self.meta_member_ID_edit.setObjectName("meta_member_ID_edit")
        self.gridLayout_2.addWidget(self.meta_member_ID_edit, 1, 1, 1, 1)
        self.version_label = QtWidgets.QLabel(self.layoutWidget1)
        self.version_label.setObjectName("version_label")
        self.gridLayout_2.addWidget(self.version_label, 2, 0, 1, 1)
        self.version_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.version_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.version_edit.setText("")
        self.version_edit.setObjectName("version_edit")
        self.gridLayout_2.addWidget(self.version_edit, 2, 1, 1, 1)
        self.modify_date_label = QtWidgets.QLabel(self.layoutWidget1)
        self.modify_date_label.setObjectName("modify_date_label")
        self.gridLayout_2.addWidget(self.modify_date_label, 3, 0, 1, 1)
        self.modify_dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        self.modify_dateEdit.setEnabled(True)
        self.modify_dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.modify_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 2, 20), QtCore.QTime(0, 0, 0)))
        self.modify_dateEdit.setObjectName("modify_dateEdit")
        self.gridLayout_2.addWidget(self.modify_dateEdit, 3, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.setting_frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(562, 120, 311, 101))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.se_ID_label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.se_ID_label_3.setObjectName("se_ID_label_3")
        self.gridLayout_3.addWidget(self.se_ID_label_3, 0, 0, 1, 1)
        self.definition_ID_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.definition_ID_edit.setEnabled(False)
        self.definition_ID_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.definition_ID_edit.setText("")
        self.definition_ID_edit.setObjectName("definition_ID_edit")
        self.gridLayout_3.addWidget(self.definition_ID_edit, 0, 1, 1, 1)
        self.generation_label = QtWidgets.QLabel(self.layoutWidget2)
        self.generation_label.setObjectName("generation_label")
        self.gridLayout_3.addWidget(self.generation_label, 1, 0, 1, 1)
        self.generation_Edit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.generation_Edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.generation_Edit.setText("")
        self.generation_Edit.setObjectName("generation_Edit")
        self.gridLayout_3.addWidget(self.generation_Edit, 1, 1, 1, 1)
        self.step_size_label = QtWidgets.QLabel(self.layoutWidget2)
        self.step_size_label.setObjectName("step_size_label")
        self.gridLayout_3.addWidget(self.step_size_label, 2, 0, 1, 1)
        self.step_size_Edit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.step_size_Edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.step_size_Edit.setText("")
        self.step_size_Edit.setObjectName("step_size_Edit")
        self.gridLayout_3.addWidget(self.step_size_Edit, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.simulation_message_label.setText(_translate("Form", "Simulation message："))
        self.start_or_pause_btn.setToolTip(_translate("Form", "<html><head/><body><p>开始</p></body></html>"))
        self.start_or_pause_btn.setWhatsThis(_translate("Form", "<html><head/><body><p>继续</p></body></html>"))
        self.stop_btn.setToolTip(_translate("Form", "<html><head/><body><p>终止</p></body></html>"))
        self.stop_btn.setWhatsThis(_translate("Form", "<html><head/><body><p>终止</p></body></html>"))
        self.progress_label.setText(_translate("Form", "Progress:"))
        item = self.member_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.member_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.member_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.member_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.member_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.member_tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.member_tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.member_tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.member_tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.member_tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.member_tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.member_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Member ID"))
        item = self.member_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Role"))
        __sortingEnabled = self.member_tableWidget.isSortingEnabled()
        self.member_tableWidget.setSortingEnabled(False)
        self.member_tableWidget.setSortingEnabled(__sortingEnabled)
        self.log_text_label.setText(_translate("Form", "mutual message:"))
        self.warning_text_log_label.setText(_translate("Form", "Warning message:"))
        self.service_msg_log_label.setText(_translate("Form", "service message:"))
        self.log_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.warning_log_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.service_msg_log_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.member_xml_path_label.setText(_translate("Form", "Member path："))
        self.members_filedialog_btn.setText(_translate("Form", "Browser..."))
        self.def_xml_path_label.setText(_translate("Form", "Simulation definition path："))
        self.def_xml_filedialog_btn.setText(_translate("Form", "Browser..."))
        self.record_dir_label.setText(_translate("Form", "Record path："))
        self.record_filedialog_btn.setText(_translate("Form", "Setting..."))
        self.label_4.setText(_translate("Form", "Primitive："))
        self.label_5.setText(_translate("Form", "Advisors："))
        self.label_6.setText(_translate("Form", "Monitors："))
        self.label_7.setText(_translate("Form", "Collective："))
        self.se_ID_label.setText(_translate("Form", "Execute ID："))
        self.se_ID_label_2.setText(_translate("Form", "Meta Member ID："))
        self.version_label.setText(_translate("Form", "Version："))
        self.modify_date_label.setText(_translate("Form", "Modify date："))
        self.modify_dateEdit.setDisplayFormat(_translate("Form", "yyyy.MM.dd"))
        self.se_ID_label_3.setText(_translate("Form", "definition ID："))
        self.generation_label.setText(_translate("Form", "Generation："))
        self.step_size_label.setText(_translate("Form", "Record step size："))

